name = "bandcamp-codes-worker"
main = "src/worker.js"
compatibility_date = "2024-09-25"
workers_dev = true

[[kv_namespaces]]
binding = "CODES"
id = "1797eac23f0743bba204ade4b04d52bf"

[triggers]
crons = ["0 6 * * *"]

[[routes]]
pattern = "mikeydorje.com/bcdl*"
zone_name = "mikeydorje.com"
